# Generated by Django 5.2.3 on 2025-06-14 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название занятия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время занятия')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название материала')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('material_type', models.CharField(choices=[('video', 'Видео (YouTube, Vimeo, Rutube)'), ('github', 'GitHub'), ('article', 'Статья/Документ'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип материала')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='lessons.lesson', verbose_name='Занятие')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='lessons.lesson', verbose_name='Занятие')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
